### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'config'

### ISSUE THREAD

**Issue by n4cr** [python-tap/pytest-tap#37]
Hi there, 
Thanks for your work.
I get the following error when I'm running `pytest --tap-stream`:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 180, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/config/__init__.py", line 617, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 306, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pytest_sugar.py", line 171, in pytest_configure
INTERNALERROR>     sugar_reporter = SugarTerminalReporter(standard_reporter)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pytest_sugar.py", line 208, in __init__
INTERNALERROR>     TerminalReporter.__init__(self, reporter.config)
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'config'
1..0
```

Any idea how this can be resolved?
Thanks

**Comment by uunbound** [comment]
Apparently you can not use sugar plugin along with tap. Pass `-p no:sugar` to your py.test command

**Comment by mblayman** [comment]
Thanks for the report!

The stream option is incompatible with other terminal reporters (such as pytest-sugar) because it needs to output proper TAP results without being in conflict with some other reporter.

If you look at https://github.com/python-tap/pytest-tap/blob/master/pytest_tap/plugin.py#L68, you can see that the plugin gets any terminal reporter and unregisters it. This is probably what is causing pytest-sugar to fail.

If you would like to use pytest-sugar *and* get TAP output, I'd suggest using a different output format like `--tap-combined`. That would dump the output to a single file.

I hope that helps!

**Comment by n4cr** [comment]
Thanks @uunbound and @mblayman. The solution propsed by @uunbound works for me as I want the tap output in stdout.
